sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake

env:
  - UBUNTU="16.04" FEATURE="HelloWorld"
  - UBUNTU="16.04" FEATURE="phpMyAdmin"
  - UBUNTU="16.04" FEATURE="WordPress"
  - UBUNTU="16.04" FEATURE="Shopware"
  - UBUNTU="17.10" FEATURE="HelloWorld"
  - UBUNTU="17.10" FEATURE="phpMyAdmin"
  - UBUNTU="17.10" FEATURE="WordPress"
  - UBUNTU="17.10" FEATURE="Shopware"
  - UBUNTU="18.04" FEATURE="HelloWorld"
  - UBUNTU="18.04" FEATURE="phpMyAdmin"
  - UBUNTU="18.04" FEATURE="WordPress"
  - UBUNTU="18.04" FEATURE="Shopware"

script:
  - docker build -t caddy-script -f Dockerfiles/$UBUNTU .
  - docker run caddy-script /bin/bash -c "export TRAVIS_CI=1; export FEATURE=$FEATURE; apt-get update; apt-get install -y curl sudo software-properties-common; bash main.sh"

after_success: |
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz &&
  cd kcov-master &&
  mkdir build &&
  cd build &&
  cmake .. &&
  make &&
  sudo make install &&
  cd ../.. &&
  rm -rf kcov-master &&
  mkdir -p coverage &&
  kcov coverage script.sh &&
  bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - vintagesucks@gmail.com